openapi: 3.0.4
info:
  title: Zip Codes Lookup
  description: Zip Codes Lookup is a simple tool for looking up the zip codes of a city. It returns the zip codes of the city.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/zipcodes:
    get:
      summary: Lookup Zip Code
      description: Zip Codes Lookup is a simple tool for looking up the zip codes of a city. It returns the zip codes of the city.
      operationId: zipcodes
      parameters:
      - name: zip
        in: query
        schema:
          type: string
        required: true
        description: The zip code for which you want to get the data (e.g., 64082)
        example: '64082'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  zipcode: '64082'
                  state_abbr: MO
                  latitude: '38.850243'
                  longitude: '-94.39570'
                  city: Lees Summit
                  state: Missouri
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
